Admin side/Models/tblProductDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace Admin_side.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
   
    public partial class tblProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductDetail()
        {
            this.tblCategoryDetails = new HashSet<tblCategoryDetail>();
        }
    
        public int ProductID { get; set; }
         [Required(ErrorMessage = "PRODUCT NAME REQUIRED")]
        public string ProductName { get; set; }
        public string ImageUrl { get; set; }

        public HttpPostedFileBase Imagefile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryDetail> tblCategoryDetails { get; set; }
    }
}

Admin side/Controllers/tblProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_side.Models;
using System.IO;

namespace Admin_side.Controllers
{
    public class tblProductDetailsController : Controller
    {
        private dbmsProject01Entities2 db = new dbmsProject01Entities2();
        public static string image;

        // GET: /tblProductDetails/
        public ActionResult Index()
        {
            return View(db.tblProductDetails.ToList());
        }

        // GET: /tblProductDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProductDetail tblproductdetail = db.tblProductDetails.Find(id);
            if (tblproductdetail == null)
            {
                return HttpNotFound();
            }
            return View(tblproductdetail);
        }

        // GET: /tblProductDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /tblProductDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(tblProductDetail product)
        {
            if (product.Imagefile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(product.Imagefile.FileName);
                string extension = Path.GetExtension(product.Imagefile.FileName);
                HttpPostedFileBase postedfile = product.Imagefile;
                int length = postedfile.ContentLength;
                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".png" || extension.ToLower() == ".jpeg")
                {
                    if (length <= 1000000)
                    {
                        fileName = fileName + extension;
                        product.ImageUrl = "~/Image/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                        product.Imagefile.SaveAs(fileName);
                        db.tblProductDetails.Add(product);

                        int a = db.SaveChanges();
                        if (a > 0)
                        {
                            ViewBag.Message = "RECORD INSERT";
                            ModelState.Clear();
                        }
                        else
                        {

                        }
                    }
                    else
                    {

                    }
                }
                else
                {

                }
                return RedirectToAction("Index");
                //fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                //product.ImageUrl = "~/Image/" + fileName;
                //fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                //product.Imagefile.SaveAs(fileName);
            }
            //if (ModelState.IsValid)
            //{
            //db.tblProductDetails.Add(product);
            //db.SaveChanges();
            //return RedirectToAction("Index");
        

            return View();
        }

    
        // GET: /tblProductDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProductDetail tblproductdetail = db.tblProductDetails.Find(id);
            image = tblproductdetail.ImageUrl;
            if (tblproductdetail == null)
            {
                return HttpNotFound();
            }
            return View(tblproductdetail);
        }

        // POST: /tblProductDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(tblProductDetail product)
        {
            if (product.Imagefile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(product.Imagefile.FileName);
                string extension = Path.GetExtension(product.Imagefile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                product.ImageUrl = "~/Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                product.Imagefile.SaveAs(fileName);
            }
            else
            {
                product.ImageUrl = image;
            }
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
            //if (product.Imagefile != null)
            //{
            //    string fileName = Path.GetFileNameWithoutExtension(product.Imagefile.FileName);
            //    string extension = Path.GetExtension(product.Imagefile.FileName);
            //    HttpPostedFileBase postedfile = product.Imagefile;
            //    int length = postedfile.ContentLength;
            //    if (extension.ToLower() == ".jpg" || extension.ToLower() == ".png" || extension.ToLower() == ".jpeg")
            //    {
            //        if (length <= 1000000)
            //        {
            //            fileName = fileName + extension;
            //            product.ImageUrl = "~/Image/" + fileName;
            //            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            //            product.Imagefile.SaveAs(fileName);
           

            //            int a = db.SaveChanges();
            //            if (a > 0)
            //            {
            //                ViewBag.Message = "RECORD INSERT";
            //                if (ModelState.IsValid)
            //                {
            //                    db.Entry(product).State = EntityState.Modified;
            //                    db.SaveChanges();
            //                    return RedirectToAction("Index");
            //                }
            //                ModelState.Clear();
            //            }
            //            else
            //            {
                            
            //            }
            //        }
            //        else
            //        {
                            
            //        }
            //    }
            //    else
            //    {
                        
            //    }
                
            //    return View(product);
                //fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                //product.ImageUrl = "~/Image/" + fileName;
                //fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                //product.Imagefile.SaveAs(fileName);
            }
            //if (ModelState.IsValid)
            //{
            //    db.tblProductDetails.Add(product);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

          
        
            
        

        // GET: /tblProductDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProductDetail tblproductdetail = db.tblProductDetails.Find(id);
            if (tblproductdetail == null)
            {
                return HttpNotFound();
            }
            return View(tblproductdetail);
        }

        // POST: /tblProductDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblProductDetail tblproductdetail = db.tblProductDetails.Find(id);
            db.tblProductDetails.Remove(tblproductdetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin side/Views/tblProductDetails/Create.cshtml
@model Admin_side.Models.tblProductDetail

@{
    ViewBag.Title = "Create";
    ViewBag.Pro = 1;
}

<h2>ADD NEW PRODUCT</h2>


@using (Html.BeginForm("Create", "tblProductDetails", FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName)
                @Html.ValidationMessageFor(model => model.ProductName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextBoxFor(model => model.Imagefile, new { type = "file" })
                @Html.ValidationMessageFor(model => model.Imagefile)*@
                <input type="file" required name="Imagefile" />
                @*@Html.EditorFor(model => model.ImageUrl)
                @Html.ValidationMessageFor(model => model.ImageUrl)*@
            </div>
        </div>

        <div class="form-group">            
            <div class="col-md-offset-2 col-md-10">                
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Admin side/Views/tblProductDetails/Delete.cshtml
@model Admin_side.Models.tblProductDetail

@{
    ViewBag.Title = "Delete";
    ViewBag.Pro = 1;
}

<h2>DELETE PRODUCT</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Admin side/Views/tblProductDetails/Details.cshtml
@model Admin_side.Models.tblProductDetail

@{
    ViewBag.Title = "Details";
    ViewBag.Pro = 1;
}

<h2>Details</h2>

<div>
    
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Admin side/Views/tblProductDetails/Edit.cshtml
@model Admin_side.Models.tblProductDetail

@{
    ViewBag.Title = "Edit";
    ViewBag.Pro = 1;
}

<h2>Update</h2>


@using (Html.BeginForm("Edit", "tblProductDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName)
                @Html.ValidationMessageFor(model => model.ProductName)
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Imagefile, new { type = "file", @id = "my-file", style = "display:none;" })
                <button type="button" onclick="document.getElementById('my-file').click()">Change Image</button>

                @Html.ValidationMessageFor(model => model.Imagefile)
                @*<input type="file"  name="Imagefile" required/>*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Admin side/Views/tblProductDetails/Index.cshtml
@model IEnumerable<Admin_side.Models.tblProductDetail>

@{
    ViewBag.Title = "Index";
    ViewBag.Pro = 1;
}

<h2 >PRODUCTS</h2>

<p >
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" >
    <tr >
        <th style="margin-left:100px;">
            @Html.DisplayNameFor(model => model.ProductName)

        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>

                <img src="@Url.Content(item.ImageUrl)" alt="Alternate Text" class="img-thumbnail" width="25%" />

            </td>
            <td>
                @*@Html.ActionLink("PRODUCTS", "Edit", new { id=item.ProductID })*@

                @Html.ActionLink("Edit", "Edit", new { id = item.ProductID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ProductID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ProductID })

            </td>
        </tr>
    }

</table>