Admin side/Models/tblCategoryDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace Admin_side.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class tblCategoryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategoryDetail()
        {
            this.tblCustDetail_Cart = new HashSet<tblCustDetail_Cart>();
            this.tblorders = new HashSet<tblorder>();
        }
    
        public int CID { get; set; }
        public Nullable<int> PID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ProductDescription { get; set; }
        [DisplayName("Upload Image")]
        public string ImageUrl { get; set; }

        public HttpPostedFileBase Imagefile { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual tblProductDetail tblProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustDetail_Cart> tblCustDetail_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblorder> tblorders { get; set; }
    }
}

Admin side/Controllers/tblCategoryDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Admin_side.Models;

namespace Admin_side.Controllers
{
    public class tblCategoryDetailController : Controller
    {
        private dbmsProject01Entities2 db = new dbmsProject01Entities2();
        public static string image;
        // GET: /tblCategoryDetail/
        public ActionResult Index()
        {
            var tblcategorydetails = db.tblCategoryDetails.Include(t => t.tblProductDetail);
            return View(tblcategorydetails.ToList());
        }

        // GET: /tblCategoryDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCategoryDetail tblcategorydetail = db.tblCategoryDetails.Find(id);
            if (tblcategorydetail == null)
            {
                return HttpNotFound();
            }
            return View(tblcategorydetail);
        }

        // GET: /tblCategoryDetail/Create
        public ActionResult Create()
        {
            ViewBag.PID = new SelectList(db.tblProductDetails, "ProductID", "ProductName");
            return View();
        }

        // POST: /tblCategoryDetail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tblCategoryDetail cat)
        {

            if (cat.Imagefile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(cat.Imagefile.FileName);
                string extension = Path.GetExtension(cat.Imagefile.FileName);
                HttpPostedFileBase postedfile = cat.Imagefile;
                int length = postedfile.ContentLength;
                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".png" || extension.ToLower() == ".jpeg")
                {
                    if (length <= 1000000)
                    {
                        fileName = fileName + extension;
                        cat.ImageUrl = "~/Image/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                        cat.Imagefile.SaveAs(fileName);
                        db.tblCategoryDetails.Add(cat);

                        int a = db.SaveChanges();
                        if (a > 0)
                        {
                            ViewBag.Message = "RECORD INSERT";
                            if (ModelState.IsValid)
                            {
                                db.Entry(cat).State = EntityState.Modified;
                                db.SaveChanges();
                                return RedirectToAction("Index");
                            }
                            ModelState.Clear();
                        }
                        else
                        {

                        }
                    }
                    else
                    {

                    }
                }
                else
                {

                }

                return View();
                //fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                //product.ImageUrl = "~/Image/" + fileName;
                //fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                //product.Imagefile.SaveAs(fileName);
            }
            //if (ModelState.IsValid)
            //{
            //    db.tblProductDetails.Add(product);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            return RedirectToAction("Index");

            //if (ModelState.IsValid)
            //{
            //    db.tblCategoryDetails.Add(tblcategorydetail);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //ViewBag.PID = new SelectList(db.tblProductDetails, "ProductID", "ProductName", tblcategorydetail.PID);
            //return View(tblcategorydetail);
        }

        // GET: /tblCategoryDetail/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCategoryDetail tblcategorydetail = db.tblCategoryDetails.Find(id);
          
            image = tblcategorydetail.ImageUrl;
            if (tblcategorydetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.PID = new SelectList(db.tblProductDetails, "ProductID", "ProductName", tblcategorydetail.PID);
            return View(tblcategorydetail);
        }

        // POST: /tblCategoryDetail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( tblCategoryDetail category)
        {
            //if (category.Imagefile != null)
            //{
            //    string fileName = Path.GetFileNameWithoutExtension(category.Imagefile.FileName);
            //    string extension = Path.GetExtension(category.Imagefile.FileName);
            //    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            //    category.ImageUrl = "~/Image/" + fileName;
            //    fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            //    category.Imagefile.SaveAs(fileName);
            //}
            //else
            //{
            //    category.ImageUrl = image;
            //}
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
            //if (ModelState.IsValid)
            //{
            //    db.Entry(tblcategorydetail).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //ViewBag.PID = new SelectList(db.tblProductDetails, "ProductID", "ProductName", tblcategorydetail.PID);
            //return View(tblcategorydetail);
        }

        // GET: /tblCategoryDetail/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCategoryDetail tblcategorydetail = db.tblCategoryDetails.Find(id);
            if (tblcategorydetail == null)
            {
                return HttpNotFound();
            }
            return View(tblcategorydetail);
        }

        // POST: /tblCategoryDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblCategoryDetail tblcategorydetail = db.tblCategoryDetails.Find(id);
            db.tblCategoryDetails.Remove(tblcategorydetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin side/Views/tblCategoryDetail/Create.cshtml
@model Admin_side.Models.tblCategoryDetail

@{
    ViewBag.Title = "Create";
    ViewBag.Category = 1;
}

<h2>ADD INVENTORY</h2>


@using (Html.BeginForm("Create", "tblCategoryDetail", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.PID, "PID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PID", String.Empty)
                @Html.ValidationMessageFor(model => model.PID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qty, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qty)
                @Html.ValidationMessageFor(model => model.Qty)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription)
                @Html.ValidationMessageFor(model => model.ProductDescription)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" required name="Imagefile" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Admin side/Views/tblCategoryDetail/Delete.cshtml
@model Admin_side.Models.tblCategoryDetail

@{
    ViewBag.Title = "Delete";
    ViewBag.Category = 1;
}

<h2>Delete</h2>

<h3 style="color:red;">Are you sure you want to delete this?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProductDetail.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProductDetail.ProductName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Admin side/Views/tblCategoryDetail/Details.cshtml
@model Admin_side.Models.tblCategoryDetail

@{
    ViewBag.Title = "Details";
    ViewBag.Category = 1;
}

<h2>Details</h2>

<div>
    
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblProductDetail.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblProductDetail.ProductName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Admin side/Views/tblCategoryDetail/Edit.cshtml
@model Admin_side.Models.tblCategoryDetail

@{
    ViewBag.Title = "Edit";
    ViewBag.Category = 1;
}

<h2>Update</h2>


@using(Html.BeginForm("Edit", "tblCategoryDetail", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.CID)

        <div class="form-group">
            @Html.LabelFor(model => model.PID, "PID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PID", String.Empty)
                @Html.ValidationMessageFor(model => model.PID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qty, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qty)
                @Html.ValidationMessageFor(model => model.Qty)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription)
                @Html.ValidationMessageFor(model => model.ProductDescription)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Imagefile, new { type = "file", @id = "my-file", style = "display:none;" })
                <button type="button" onclick="document.getElementById('my-file').click()">Change Image</button>

                @Html.ValidationMessageFor(model => model.Imagefile)
                @*@Html.EditorFor(model => model.ImageUrl)
                @Html.ValidationMessageFor(model => model.ImageUrl)*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Admin side/Views/tblCategoryDetail/Index.cshtml
@model IEnumerable<Admin_side.Models.tblCategoryDetail>

@{
    ViewBag.Title = "Index";
    ViewBag.Category = 1;
}

<h2>INVENTORY</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tblProductDetail.ProductName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductDescription)
        </td>
        <td>
            @if (item.ImageUrl != null)
            {
                     <img src="@Url.Content(item.ImageUrl)" alt="Alternate Text" class="img-thumbnail" width="55%" />
            }
        
       
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblProductDetail.ProductName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CID })
        </td>
    </tr>
}

</table>