Admin side/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_side.Models;

namespace Admin_side.Controllers
{
    public class PaymentController : Controller
    {
        private dbmsProject01Entities2 db = new dbmsProject01Entities2();

        // GET: /Payment/
        public ActionResult Index()
        {
            return View(db.tblPayment_Details.ToList());
        }

        // GET: /Payment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPayment_Details tblpayment_details = db.tblPayment_Details.Find(id);
            if (tblpayment_details == null)
            {
                return HttpNotFound();
            }
            return View(tblpayment_details);
        }

        // GET: /Payment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Payment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="PaymentID,Name,AccNumber,BankName,Mode,CvvNo")] tblPayment_Details tblpayment_details)
        {
            if (ModelState.IsValid)
            {
                db.tblPayment_Details.Add(tblpayment_details);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblpayment_details);
        }

        // GET: /Payment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPayment_Details tblpayment_details = db.tblPayment_Details.Find(id);
            if (tblpayment_details == null)
            {
                return HttpNotFound();
            }
            return View(tblpayment_details);
        }

        // POST: /Payment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="PaymentID,Name,AccNumber,BankName,Mode,CvvNo")] tblPayment_Details tblpayment_details)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblpayment_details).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblpayment_details);
        }

        // GET: /Payment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPayment_Details tblpayment_details = db.tblPayment_Details.Find(id);
            if (tblpayment_details == null)
            {
                return HttpNotFound();
            }
            return View(tblpayment_details);
        }

        // POST: /Payment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblPayment_Details tblpayment_details = db.tblPayment_Details.Find(id);
            db.tblPayment_Details.Remove(tblpayment_details);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin side/Controllers/orderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_side.Models;

namespace Admin_side.Controllers
{
    public class orderController : Controller
    {
        private dbmsProject01Entities2 db = new dbmsProject01Entities2();

        // GET: /order/
        public ActionResult Index()
        {
            var tblorders = db.tblorders.Include(t => t.tbl_costumerdetails).Include(t => t.tblCategoryDetail).Include(t => t.tblPayment_Details);
            return View(tblorders.ToList());
        }

        // GET: /order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblorder tblorder = db.tblorders.Find(id);
            if (tblorder == null)
            {
                return HttpNotFound();
            }
            return View(tblorder);
        }

        // GET: /order/Create
        public ActionResult Create()
        {
            ViewBag.UID = new SelectList(db.tbl_costumerdetails, "CID", "FirstName");
            ViewBag.CID = new SelectList(db.tblCategoryDetails, "CID", "Name");
            ViewBag.PID = new SelectList(db.tblPayment_Details, "PaymentID", "Name");
            return View();
        }

        // POST: /order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="OID,PID,UID,CID,status,Bill,Address")] tblorder tblorder)
        {
            if (ModelState.IsValid)
            {
                db.tblorders.Add(tblorder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UID = new SelectList(db.tbl_costumerdetails, "CID", "FirstName", tblorder.UID);
            ViewBag.CID = new SelectList(db.tblCategoryDetails, "CID", "Name", tblorder.CID);
            ViewBag.PID = new SelectList(db.tblPayment_Details, "PaymentID", "Name", tblorder.PID);
            return View(tblorder);
        }

        // GET: /order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblorder tblorder = db.tblorders.Find(id);
            if (tblorder == null)
            {
                return HttpNotFound();
            }
            ViewBag.UID = new SelectList(db.tbl_costumerdetails, "CID", "FirstName", tblorder.UID);
            ViewBag.CID = new SelectList(db.tblCategoryDetails, "CID", "Name", tblorder.CID);
            ViewBag.PID = new SelectList(db.tblPayment_Details, "PaymentID", "Name", tblorder.PID);
            return View(tblorder);
        }

        // POST: /order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="OID,PID,UID,CID,status,Bill,Address")] tblorder tblorder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblorder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UID = new SelectList(db.tbl_costumerdetails, "CID", "FirstName", tblorder.UID);
            ViewBag.CID = new SelectList(db.tblCategoryDetails, "CID", "Name", tblorder.CID);
            ViewBag.PID = new SelectList(db.tblPayment_Details, "PaymentID", "Name", tblorder.PID);
            return View(tblorder);
        }

        // GET: /order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblorder tblorder = db.tblorders.Find(id);
            if (tblorder == null)
            {
                return HttpNotFound();
            }
            return View(tblorder);
        }

        // POST: /order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblorder tblorder = db.tblorders.Find(id);
            db.tblorders.Remove(tblorder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin side/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="img/favicon.ico" rel="icon">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    
    <link href="~/Template/lib/animate/animate.min.css" rel="stylesheet" />
    <script src="~/Template/lib/owlcarousel/owl.carousel.min.js"></script>
    <link href="~/Template/css/style.css" rel="stylesheet" />
    <!-- Customized Bootstrap Stylesheet -->
   

</head>
<body style="padding-top:10px;">
    <div class="container-fluid bg-dark mb-30">
        <div class="row px-xl-5" >
            <div class="row align-items-center bg-dark py-3 px-xl-1 d-none d-lg-flex">
                <div class="col-lg-20" >
                    
                    @Html.ActionLink("ASUB", "Index", "Home", null, new { @class = "h1 text-uppercase text-primary bg-dark px-2" })
                    @Html.ActionLink("MART", "Index", "Home", null, new { @class = "h1 text-uppercase text-light bg-primary px-2 ml-n1" })
                </div>
            </div>


            <div class="col-lg-7" style="  font-size:18px; margin-top:15px;">

                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">

                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">


                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("PRODUCT", "Index", "tblProductDetails")</li>
                                <li>@Html.ActionLink("ORDER", "Index", "order")</li>
                                <li>@Html.ActionLink("INVENTORY", "Index", "tblCategoryDetail")</li>
                                <li>@Html.ActionLink("PAYMENT", "Index", "Payment")</li>
                            </ul>

                            <!--MVC NAVBAR-->

                        </div>

                    </div>
                </nav>
            </div>
        </div>
    </div>
    
    <div class="container body-content">
        @if (ViewBag.Pro == 1 || ViewBag.Category==1 || ViewBag.Order==1 || ViewBag.Pay==1)
        {
            @RenderBody()
        }
        else
        {

            @RenderBody()
        <!-- Carousel Start -->
            <div class="container-fluid mb-3">
                <div class="row px-xl-5">
                    <div class="col-lg-8">
                        <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">

                            <div class="carousel-inner">
                                <div class="carousel-item position-relative active" style="height: 430px;">

                                    <img class="position-absolute w-100 h-100" src="~/Template/img/carousel-1.jpg" style="object-fit: cover;" />

                                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                        <div class="p-3" style="max-width: 700px;">
                                            <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">PRODUCTS</h1>
                                            <p class="mx-md-5 px-5 animate__animated animate__bounceIn">All your Needs are here :)</p>
                                            <p class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp">@Html.ActionLink("PRODUCT", "Index", "tblProductDetails")</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item position-relative" style="height: 430px;">


                                    <img class="position-absolute w-100 h-100" src="~/Template/img/carousel-2.jpg" style="object-fit: cover;" />

                                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                        <div class="p-3" style="max-width: 700px;">
                                            <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Women Fashion</h1>
                                            <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                            <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item position-relative" style="height: 430px;">
                                    <img class="position-absolute w-100 h-100" src="~/Template/img/carousel-3.jpg" style="object-fit: cover;">
                                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                        <div class="p-3" style="max-width: 700px;">
                                            <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Kids Fashion</h1>
                                            <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                            <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="product-offer mb-30" style="height: 200px;">

                            <img class="img-fluid" src="~/Template/img/pexels-melvin-buezo-2529148.jpg" />
                            <div class="offer-text">
                                <h3 class="text-white mb-3">CATEGORY 1</h3>
                                <p class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp">@Html.ActionLink("Category 1", "Index", "tblCategoryDetail")</p>
                            </div>
                        </div>
                        <div class="product-offer mb-30" style="height: 200px;">


                            <img class="img-fluid" src="~/Template/img/icons8-team-seDjj4dmC9s-unsplash.jpg" />
                            <div class="offer-text">

                                <h3 class="text-white mb-3">CATEGORY 2</h3>
                                <p class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp">@Html.ActionLink("Category 2", "Index", "tblCategoryDetail")</p>

                            </div>
                        </div>
                    </div>
                </div>

                <!-- Carousel End -->
               


            </div>


        }

    </div>
    <!--FOOTER START-->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Plot 123 Street,Karachi, Pakistan </p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>AnasVayani1403@gmail.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+0345 6789000 Emergemcy Call Only :)</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Your Email Address">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                        </form>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy;ASUB MART MANAGEMENT. All Rights Reserved. Designed by 
                    <a class="text-primary" href="http://localhost:49794/Home/Index">ASUB Mart Management</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    
    <!-- NAVBAR Complete Above -->

  
       @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>